name: medallion
profile: medallion
version: "1.0.0"
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
docs-paths: ["docs"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  medallion:
    bronze_to_silver:
      +schema: silver
      +materialized: table
    silver_to_gold:
      +schema: gold
      +materialized: table
